language: php

env:
  - APP_ENV=travis

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install --no-interaction

script:
  - phpunit

matrix:
  allow_failures:
    - php: 5.3.3
